vim.wo.number=true
vim.o.smarttab=true
vim.o.cursorline=true
vim.o.pumblend=20
vim.o.clipboard = "unnamed,unnamedplus"
vim.o.completeopt = "menuone,noinsert,noselect"
vim.o.tabstop = 2
vim.o.signcolumn = "yes" -- これを設定しないとvgitでガタつく
vim.updatetime = 300
vim.o.incsearch = false
